### ISSUE TITLE
I can't run the heroku link provided

### ISSUE THREAD

**Issue by jugaldb** [abhishekvispute/paaradarshak-chainrunner#1]
Hey, I was going through your project, I tried to visit the heroku link provided, it is just stuck on a preloader which says loading WEB3, accounts and contracts, I hope you can help me out here

Thanks

**Comment by abhishekvispute** [comment]
Hey Hi,
Yep, it must have stuck because smart contracts were deployed on Matic's testnetv3.
And now they deprecated that net, hence this.
Now Moving forward, either you can deploy it locally as given in Instructions 

Truffle Migration Local Network
$ truffle migrate

That's All
If you require more assistance, do let me know.

(I have removed the link now)
Thanks

**Comment by jugaldb** [comment]
Hey @abhishekvispute, thanks for replying,  I am new to matic and blockchain in general, I was able to generate the mnemonic using metamask but am facing some issues in running truffle develop, I get the following error while running the
 `truffle develop` command

```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```

I hope you can help me sort this out, I know this is an old project of yours, but it would be great if you could help me out, thanks
